//
// Created by stan1 on 12/12/2025.
//

#ifndef SPRITE_IDS_H
#define SPRITE_IDS_H

namespace sprites {
enum class Sprite_ID {

  // PACMAN
  PACMAN_IDLE,
  PACMAN_RIGHT_1,
  PACMAN_RIGHT_2,
  PACMAN_LEFT_1,
  PACMAN_LEFT_2,
  PACMAN_UP_1,
  PACMAN_UP_2,
  PACMAN_DOWN_1,
  PACMAN_DOWN_2,
  // -----------
  PACMAN_DYING_1,
  PACMAN_DYING_2,
  PACMAN_DYING_3,
  PACMAN_DYING_4,
  PACMAN_DYING_5,
  PACMAN_DYING_6,
  PACMAN_DYING_7,
  PACMAN_DYING_8,
  PACMAN_DYING_9,
  PACMAN_DYING_10,
  PACMAN_DYING_11,
  PACMAN_DYING_12,

  // RED GHOST
  GHOST_RED_RIGHT_1,
  GHOST_RED_RIGHT_2,
  GHOST_RED_LEFT_1,
  GHOST_RED_LEFT_2,
  GHOST_RED_UP_1,
  GHOST_RED_UP_2,
  GHOST_RED_DOWN_1,
  GHOST_RED_DOWN_2,

  // BLUE GHOST
  GHOST_BLUE_RIGHT_1,
  GHOST_BLUE_RIGHT_2,
  GHOST_BLUE_LEFT_1,
  GHOST_BLUE_LEFT_2,
  GHOST_BLUE_UP_1,
  GHOST_BLUE_UP_2,
  GHOST_BLUE_DOWN_1,
  GHOST_BLUE_DOWN_2,

  // WHITE GHOST
  GHOST_WHITE_RIGHT_1,
  GHOST_WHITE_RIGHT_2,
  GHOST_WHITE_LEFT_1,
  GHOST_WHITE_LEFT_2,
  GHOST_WHITE_UP_1,
  GHOST_WHITE_UP_2,
  GHOST_WHITE_DOWN_1,
  GHOST_WHITE_DOWN_2,

  // YELLOW GHOST
  GHOST_YELLOW_RIGHT_1,
  GHOST_YELLOW_RIGHT_2,
  GHOST_YELLOW_LEFT_1,
  GHOST_YELLOW_LEFT_2,
  GHOST_YELLOW_UP_1,
  GHOST_YELLOW_UP_2,
  GHOST_YELLOW_DOWN_1,
  GHOST_YELLOW_DOWN_2,

  // FEAR MODE
  GHOST_FEAR_BLUE_1,
  GHOST_FEAR_BLUE_2,
  GHOST_FEAR_FLASH_1,
  GHOST_FEAR_FLASH_2,

  // GHOST EYES
  GHOST_EYES_RIGHT,
  GHOST_EYES_LEFT,
  GHOST_EYES_UP,
  GHOST_EYES_DOWN,

  // ORBS
  ORB_SMALL,
  ORB_BIG,

  // FRUITS
  FRUIT_CHERRY,
  FRUIT_STRAWBERRY,
  FRUIT_ORANGE,
  FRUIT_APPLE,
  FRUIT_MELON,
  FRUIT_GALAXIAN,
  FRUIT_BELL,
  FRUIT_KEY,

  // WHITE SCORES
  WHITE_200,
  WHITE_400,
  WHITE_800,
  WHITE_1600,

  // BLUE SCORES
  BLUE_100,
  BLUE_300,
  BLUE_500,
  BLUE_700,
  BLUE_1000,
  BLUE_2000,
  BLUE_3000,
  BLUE_5000,

  // COUNT
  COUNT // <- to resize vector correctly
};
}

#endif // SPRITE_IDS_H
